#!/usr/bin/env python3
"""Generate or check the FR-to-test traceability matrix."""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from pathlib import Path

FR_DOC = Path("docs/FUNCTIONAL_REQUIREMENTS.md")
MATRIX_DOC = Path("docs/reference/fr_coverage_matrix.md")

FR_HEADING_RE = re.compile(r"^### (FR-AGENT_USER_STATUS-\d{3})$", re.MULTILINE)
STATUS_RE = re.compile(r"\*\*Status:\*\* (IMPLEMENTED|PARTIAL|SCAFFOLD)")
DESCRIPTION_RE = re.compile(r"\*\*Description:\*\* (.+)")
CANONICAL_MARKER_RE = re.compile(r'@pytest\.mark\.requirement\("((?:FR-AGENT_USER_STATUS)-\d{3})"\)')
LEGACY_MARKER_RE = re.compile(r'@pytest\.mark\.requirement\("(FR-age-\d{3})"\)')


def parse_requirements() -> list[tuple[str, str, str]]:
    text = FR_DOC.read_text(encoding="utf-8")
    headings = list(FR_HEADING_RE.finditer(text))
    requirements: list[tuple[str, str, str]] = []
    for index, heading in enumerate(headings):
        end = headings[index + 1].start() if index + 1 < len(headings) else len(text)
        block = text[heading.end() : end]
        description = DESCRIPTION_RE.search(block)
        status = STATUS_RE.search(block)
        if description and status:
            requirements.append((heading.group(1), description.group(1), status.group(1)))
    return requirements


def collect_markers() -> tuple[dict[str, list[str]], dict[str, list[str]], list[str]]:
    by_requirement: dict[str, list[str]] = defaultdict(list)
    legacy: dict[str, list[str]] = defaultdict(list)
    orphan_files: list[str] = []
    for path in sorted(Path("tests").rglob("test_*.py")):
        text = path.read_text(encoding="utf-8")
        canonical_markers = CANONICAL_MARKER_RE.findall(text)
        legacy_markers = LEGACY_MARKER_RE.findall(text)
        if not canonical_markers and not legacy_markers:
            orphan_files.append(str(path))
        for marker in canonical_markers:
            by_requirement[marker].append(str(path))
        for marker in legacy_markers:
            legacy[marker].append(str(path))
    return by_requirement, legacy, orphan_files


def requirement_notes(fr_id: str, status: str, files: list[str]) -> str:
    if fr_id == "FR-AGENT_USER_STATUS-004" and files:
        return (
            "TTL cache hit, expiry, copy isolation, bounded eviction, subprocess-backed "
            "statusd caching, and invalidation covered."
        )
    if fr_id == "FR-AGENT_USER_STATUS-007" and files:
        return (
            "Browser monitor UI, `/monitor` route, privacy route, derived eye-state "
            "data contract, and native tray/popup source coverage."
        )
    if status == "SCAFFOLD" and not files:
        return "Scaffold without direct tests yet."
    return ""


def render_matrix() -> str:
    requirements = parse_requirements()
    by_requirement, legacy, orphan_files = collect_markers()
    covered = sum(1 for fr_id, _description, _status in requirements if by_requirement.get(fr_id))

    lines = [
        "<!-- GENERATED by scripts/update-fr-matrix.py --write; do not edit by hand. -->",
        "",
        "# FR-to-Test Traceability Matrix",
        "",
        "## Summary",
        "",
        f"- **Total canonical FRs:** {len(requirements)}",
        f"- **Covered (>=1 canonical marker):** {covered}",
        f"- **Missing canonical marker coverage:** {len(requirements) - covered}",
        f"- **Noncanonical requirement markers:** {sum(len(values) for values in legacy.values())}",
        f"- **Orphan test files:** {len(orphan_files)}",
        "",
        "## Coverage Matrix",
        "",
        "| FR ID | Description | Requirement Status | Coverage Status | "
        "Canonical Test Count | Canonical Test Files | Notes |",
        "|-------|-------------|--------------------|-----------------|----------------------|----------------------|-------|",
    ]
    for fr_id, description, status in requirements:
        files = sorted(set(by_requirement.get(fr_id, [])))
        count = len(by_requirement.get(fr_id, []))
        coverage = "COVERED" if files else "MISSING"
        files_cell = "<br>".join(f"`{file}`" for file in files) if files else "(none)"
        notes = requirement_notes(fr_id, status, files)
        lines.append(f"| `{fr_id}` | {description} | {status} | {coverage} | {count} | {files_cell} | {notes} |")

    lines.extend(["", "## Noncanonical Marker Debt", ""])
    if legacy:
        lines.extend(
            [
                "| Marker ID | Marked Test Count | Test Files | Recommended Action |",
                "|-----------|-------------------|------------|--------------------|",
            ]
        )
        for marker, files in sorted(legacy.items()):
            files_cell = "<br>".join(f"`{file}`" for file in sorted(set(files)))
            lines.append(f"| `{marker}` | {len(files)} | {files_cell} | Map to `FR-AGENT_USER_STATUS-*`. |")
    else:
        lines.append("No noncanonical requirement markers remain.")

    lines.extend(["", "## Orphan Test Files", ""])
    if orphan_files:
        lines.extend(f"- `{file}`" for file in orphan_files)
    else:
        lines.append("No orphan test files without requirement markers remain.")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="Fail if the checked-in matrix is stale")
    mode.add_argument("--write", action="store_true", help="Rewrite the checked-in matrix")
    args = parser.parse_args()

    rendered = render_matrix()
    if args.write:
        MATRIX_DOC.write_text(rendered, encoding="utf-8")
        print(f"updated {MATRIX_DOC}")
        return 0

    current = MATRIX_DOC.read_text(encoding="utf-8") if MATRIX_DOC.exists() else ""
    if current != rendered:
        print(f"{MATRIX_DOC} is stale; run scripts/update-fr-matrix.py --write")
        return 1
    print(f"{MATRIX_DOC} is current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
